language: node_js
node_js:
  - "8"
script:
  npm install;
  hexo g
deploy:
  provider: pages
  skip_cleanup: true
  repo: soulomoon/soulomoon.github.io
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
